name: CI/CD Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login to Docker Hub (Optional if you want to push)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build API Docker image
    - name: Build API Docker Image
      run: |
        docker build -t 95mary25/cancer-prediction-api:latest -f docker/Dockerfile_api .

    # Build UI Docker image
    - name: Build UI Docker Image
      run: |
        docker build -t 95mary25/cancer-prediction-ui:latest -f docker/Dockerfile_ui .

    # Optional: Push Docker images to Docker Hub
    - name: Push API Image
      run: |
        docker tag 95mary25/cancer-prediction-api:latest 95mary25/cancer-prediction-api:latest
        docker push 95mary25/cancer-prediction-api:latest

    - name: Push UI Image
      run: |
        docker tag 95mary25/cancer-prediction-ui:latest 95mary25/cancer-prediction-ui:latest
        docker push 95mary25/cancer-prediction-ui:latest

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train Model
      run: python src/model.py

    # Run pytest integration tests
    - name: Run pytest
      run: |
        
        pip install pytest

    - name: Lint Python files
      run: pylint --disable=R,C,W1203,W1202,W0613 src/
      

    - name: Run Tests
      run: pytest -v
